version = 1

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"
type = "python"
max_line_length = 100
root = "."

#[[transformers]]
#name = "autopep8"
#enabled = true
